import {normalize,generate,newKey,esc,safetyLabel,matches,projectOptions} from './renderer.js';
import {initProfile,renderProfilePreview,getProfile,replaceProfile,flushProfile} from './profile-ui.js';
import {normalizeProfile} from './profile.js';
const $=id=>document.getElementById(id),STORE='mint-comment-mobile-v1',BACKUP=STORE+'-previous';
let records=[],active='',output='',view='library',mode='comment',timer,messageTimer,dirty=false,loadFailed=false;
const PREVIEW={comment:'preview',profile:'p-preview'},HOME={comment:'library',profile:'p-basic'},lastView={comment:'library',profile:'p-basic'},wideMQ=matchMedia('(min-width:1100px)');
const visible=id=>!$(id).hidden;
const current=()=>records.find(r=>r.key===active);
function say(s){$('message').textContent=s;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').textContent='',6500);}
function save(){clearTimeout(timer);try{if(loadFailed)throw Error();const previous=localStorage.getItem(STORE);if(previous)localStorage.setItem(BACKUP,previous);localStorage.setItem(STORE,JSON.stringify({active,records}));dirty=false;$('save-state').textContent='이 기기에 자동 저장됨';return true;}catch{$('save-state').textContent='기기 저장 실패 · JSON으로 백업해 주세요';dirty=true;return false;}}
function changed(){dirty=true;$('save-state').textContent='저장 중…';clearTimeout(timer);timer=setTimeout(save,350);if(view==='theme'||visible('preview'))renderPreview();}
// PC 넓은 화면에서는 편집 화면 오른쪽에 미리보기를 함께 둠
function switchView(next){const wide=wideMQ.matches;if(wide&&next===PREVIEW[mode])next=lastView[mode]!==next?lastView[mode]:(mode==='comment'?'edit':'p-basic');view=lastView[mode]=next;document.body.classList.toggle('wide',wide);document.querySelectorAll('.screen').forEach(s=>{const side=wide&&s.id===PREVIEW[mode];s.hidden=!(s.id===next||side);s.classList.toggle('side',side);});$('nav-comment').hidden=mode!=='comment';$('nav-profile').hidden=mode!=='profile';document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(next==='library')renderList();if(mode==='comment'&&(next==='theme'||visible('preview')))renderPreview();if(mode==='profile'&&visible('p-preview'))renderProfilePreview();window.scrollTo(0,0);}
function setMode(m){if(dirty)save();flushProfile();mode=m;try{localStorage.setItem('lumo-studio-mode',m);}catch{}$('mode-title').textContent=m==='comment'?'제작자 코멘트':'제작자 소개페이지';document.querySelectorAll('[data-mode]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',String(b.dataset.mode===m));});switchView(lastView[m]);}
function refreshFolders(){const old=$('project-filter').value,names=projectOptions(records);$('project-filter').innerHTML='<option value="all">전체 프로젝트</option><option value="unfiled">미분류</option>'+names.map(n=>`<option value="${esc('p:'+n)}">📁 ${esc(n)} (${records.filter(r=>r.project===n).length})</option>`).join('');$('project-filter').value=[...$('project-filter').options].some(o=>o.value===old)?old:'all';$('project-names').innerHTML=names.map(n=>`<option value="${esc(n)}"></option>`).join('');$('rename-project').disabled=!$('project-filter').value.startsWith('p:');$('export-project').disabled=$('project-filter').value==='all';}
function renderList(){refreshFolders();const shown=records.filter(r=>matches(r,$('project-filter').value,$('safety-filter').value,$('search').value));$('result-count').textContent=shown.length+'개 / 전체 '+records.length+'개';$('characters').innerHTML=shown.map(r=>`<article class="character ${r.key===active?'selected':''}"><div class="symbol" style="background:${r.color}" aria-hidden="true">${esc(r.emoji1)}</div><div class="info"><h3>${esc(r.work||'이름 없는 캐릭터')}</h3><p class="small">📁 ${esc(r.project||'미분류')} · <span class="badge ${r.safety}">${safetyLabel(r.safety)}</span></p><p class="small">업데이트 ${r.patches.length}개</p><div class="tools"><button data-open="${r.key}">편집</button><button data-duplicate="${r.key}">복제</button><button data-remove="${r.key}" aria-label="${esc(r.work)} 삭제">삭제</button></div></div></article>`).join('')||("<p class='box'>조건에 맞는 캐릭터가 없습니다. 폴더나 라벨을 바꿔 보세요.</p>");}
function populate(){refreshFolders();const d=current();for(const k of ['work','project','safety','creator','comment','bgm','color','emoji1','emoji2','tone'])$(k).value=d[k];$('hex').value=d.color;renderPatches();renderPreview();}
function renderPatches(){$('patches').innerHTML=current().patches.map((p,i)=>`<details class="patch" ${i===0?'open':''}><summary>${esc(p.date||'날짜 미지정')} · ${esc(p.title||'새 업데이트')}</summary>${['date','title','added','changed','note'].map((k,n)=>`<label for="patch-${i}-${k}">${['날짜','제목','추가한 내용','수정한 내용','덧붙일 코멘트'][n]}</label>${n<2?`<input id="patch-${i}-${k}" type="${k==='date'?'date':'text'}" data-index="${i}" data-key="${k}" value="${esc(p[k])}">`:`<textarea id="patch-${i}-${k}" rows="3" data-index="${i}" data-key="${k}">${esc(p[k])}</textarea>`}`).join('')}<button class="delete-patch" data-delete="${i}">이 기록 삭제</button></details>`).join('');}
function previewDoc(html){return '<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:6px;background:#f1f2ed">'+html+'</body></html>';}
function renderPreview(){output=generate(current());$('code').value=output;const over=output.length>50000;$('copy').disabled=$('html-save').disabled=over;$('count').textContent=output.length.toLocaleString()+' / 50,000자';$('limit').textContent=over?'50,000자를 넘었습니다. 코멘트나 이전 기록을 줄여 주세요.':'공백과 HTML 코드를 포함한 글자 수입니다.';$('limit').classList.toggle('danger',over);if(visible('preview'))$('frame').srcdoc=previewDoc(output);if(view==='theme'){let frame=$('theme-preview').querySelector('iframe');if(!frame){frame=document.createElement('iframe');frame.title='색상과 이모지 헤더 미리보기';frame.setAttribute('sandbox','');$('theme-preview').append(frame);}const noFont=output.replace(/@import[^;]+;/g,'');frame.srcdoc=previewDoc(noFont+'<style>.mcc-body,.mcc-patches,.mcc-divider,.mcc-status{display:none!important}</style>');}}
const safeName=()=> ((current().work||'character')+(current().safety==='unspecified'?'':'_'+safetyLabel(current().safety))).replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_');
async function download(text,name,type){const blob=new Blob([text],{type}),file=new File([blob],name,{type});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:name});return;}catch(e){if(e.name==='AbortError')return;}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);say('파일 저장 위치를 확인해 주세요.');}
function addRecord(r){r.key=newKey();records.unshift(r);active=r.key;save();populate();switchView('edit');}
$('new').onclick=()=>addRecord(normalize({work:'새 캐릭터',project:$('project-filter').value.startsWith('p:')?$('project-filter').value.slice(2):'',safety:$('safety-filter').value,creator:'m1nch0wh4ck',comment:'',bgm:'',color:'#00efb2',emoji1:'👽',emoji2:'✦',patches:[]}));
$('characters').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){active=b.dataset.open;save();populate();switchView('edit');}if(b.dataset.duplicate){addRecord(normalize({...records.find(r=>r.key===b.dataset.duplicate),work:records.find(r=>r.key===b.dataset.duplicate).work+' (복사)'}));}if(b.dataset.remove){const r=records.find(r=>r.key===b.dataset.remove);if(!confirm(`‘${r.work}’을 삭제할까요? 필요한 내용은 먼저 JSON으로 백업해 주세요.`))return;records=records.filter(x=>x.key!==r.key);if(!records.length)records=[normalize({work:'새 캐릭터',creator:'m1nch0wh4ck',patches:[]})];if(active===r.key)active=records[0].key;save();populate();renderList();}};
for(const k of ['work','project','safety','creator','comment','bgm','color','emoji1','emoji2','tone'])$(k).addEventListener('input',()=>{current()[k]=k==='project'?$(k).value.trim():$(k).value;if(k==='color')$('hex').value=current().color;changed();});
$('hex').oninput=()=>{const valid=/^#[0-9a-f]{6}$/i.test($('hex').value);$('hex').setCustomValidity(valid?'':'# 뒤에 6자리 색상 코드를 입력하세요.');if(valid){current().color=$('hex').value;$('color').value=current().color;changed();}};
$('shuffle').onclick=()=>{current().seed=(current().seed+1)|0;changed();};
$('patches').oninput=e=>{const {index,key}=e.target.dataset;if(key){current().patches[Number(index)][key]=e.target.value;const p=current().patches[Number(index)];e.target.closest('details').querySelector('summary').textContent=(p.date||'날짜 미지정')+' · '+(p.title||'새 업데이트');changed();}};
$('patches').onclick=e=>{const b=e.target.closest('[data-delete]');if(b&&confirm('이 업데이트 기록을 삭제할까요?')){current().patches.splice(Number(b.dataset.delete),1);renderPatches();changed();}};
$('add-patch').onclick=()=>{const d=new Date(),date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');current().patches.unshift({date,title:'',added:'',changed:'',note:''});renderPatches();changed();$('patch-0-title').focus();};
$('export').onclick=()=>download(JSON.stringify(current(),null,2),safeName()+'.json','application/json');
$('backup').onclick=()=>download(JSON.stringify({format:'mint-comment-collection',version:2,records},null,2),'mint-comment-backup.json','application/json');
// 코멘트 개별(version 3 이하)·묶음(version 2 이하)만 코멘트로 받음. 모르는 형식·버전은 거부
function commentItems(v){if(v&&typeof v==='object'&&'format'in v){if(v.format!=='mint-comment-collection')return null;if(!Number.isInteger(v.version)||v.version>2)throw Error('지원하지 않는 코멘트 묶음 JSON 버전입니다.');if(!Array.isArray(v.records)||!v.records.length)throw Error('캐릭터가 포함된 백업을 선택해 주세요.');return v.records.map(normalize);}if(v&&typeof v==='object'&&'version'in v&&(!Number.isInteger(v.version)||v.version>3))throw Error('지원하지 않는 코멘트 JSON 버전입니다.');return [normalize(v)];}
function addComments(items){const used=new Set(records.map(r=>r.key));items.forEach(r=>{if(used.has(r.key))r.key=newKey();used.add(r.key);});records.unshift(...items);active=items[0].key;save();populate();renderList();}
function takeProfile(v){if(!confirm('소개페이지를 불러온 파일 내용으로 바꿀까요? 지금 내용은 이 기기에 직전 사본으로 남습니다. 필요하면 먼저 ‘소개페이지 JSON’으로 저장해 주세요.'))return false;if(!replaceProfile(v))throw Error('기기 저장에 실패해 소개페이지를 바꾸지 않았습니다.');return true;}
async function importFile(f){if(f.size>10000000)throw Error('10MB 이하의 JSON 파일을 선택해 주세요.');let v;try{v=JSON.parse(await f.text());}catch{throw Error('JSON 파일을 읽을 수 없습니다.');}
 if(v?.format==='lumo-studio-backup'){if(v.version!==1)throw Error('지원하지 않는 스튜디오 백업 버전입니다. 루모 스튜디오를 업데이트해 주세요.');const items=v.comments==null?[]:commentItems(v.comments);if(items===null)throw Error('백업 안의 코멘트 데이터 형식이 다릅니다.');const prof=v.profile==null?null:normalizeProfile(v.profile);const took=prof?takeProfile(prof):false;if(items.length)addComments(items);return `전체 백업: 코멘트 ${items.length}개 추가${prof?(took?', 소개페이지 교체':', 소개페이지는 유지'):''}`;}
 if(v?.format==='lumo-creator-profile'){const prof=normalizeProfile(v);return takeProfile(prof)?'소개페이지를 불러왔습니다.':'불러오기를 취소했습니다.';}
 const items=commentItems(v);if(items===null)throw Error('루모 스튜디오에서 저장한 JSON 파일이 아닙니다.');addComments(items);return items.length+'개 캐릭터를 별도로 추가했습니다.';}
$('import').onclick=()=>$('file').click();document.querySelectorAll('.import-any').forEach(b=>b.onclick=()=>$('file').click());
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{say(await importFile(f));}catch(err){say(err.message);}finally{e.target.value='';}};
document.querySelectorAll('.studio-backup').forEach(b=>b.onclick=()=>{if(dirty)save();flushProfile();download(JSON.stringify({format:'lumo-studio-backup',version:1,exportedAt:new Date().toISOString(),comments:{format:'mint-comment-collection',version:2,records},profile:getProfile()},(k,v)=>k==='open'?undefined:v,2),'lumo-studio-backup.json','application/json');});
$('copy').onclick=async()=>{renderPreview();if(output.length>50000)return;try{await navigator.clipboard.writeText(output);say('HTML을 복사했습니다. 루모 제작자 코멘트에 붙여넣어 주세요.');}catch{$('code-details').open=true;$('code').focus();$('code').select();$('code').setSelectionRange(0,output.length);say('코드를 길게 눌러 복사해 주세요.');}};
$('select-code').onclick=()=>{$('code').focus();$('code').select();$('code').setSelectionRange(0,output.length);};
$('html-save').onclick=()=>{renderPreview();if(output.length<=50000)download(output,safeName()+'-comment.html','text/html');};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));wideMQ.addEventListener('change',()=>switchView(view));
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(dirty)save();flushProfile();}});window.addEventListener('pagehide',()=>{if(dirty)save();flushProfile();});window.addEventListener('beforeunload',e=>{if(dirty&&!save()){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===STORE){loadFailed=true;$('save-state').textContent='다른 창에서 변경됨 · 현재 내용은 JSON 백업 후 다시 열어 주세요';say('다른 창의 작업을 보호하기 위해 자동 저장을 멈췄습니다.');}});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true;}};
async function init(){try{const raw=localStorage.getItem(STORE);if(raw){const s=JSON.parse(raw);if(!Array.isArray(s.records)||!s.records.length)throw Error();records=s.records.map(normalize);active=records.some(r=>r.key===s.active)?s.active:records[0].key;}}catch{loadFailed=true;$('save-state').textContent='저장 내용 읽기 실패 · 기존 저장소는 덮어쓰지 않습니다';say('저장 내용을 읽지 못했습니다. 보관한 JSON을 불러와 주세요.');}
if(!records.length){try{records=[normalize(await(await fetch('./sample.json')).json())];}catch{records=[normalize({work:'새 캐릭터',creator:'m1nch0wh4ck',patches:[]})];}active=records[0].key;}
populate();renderList();if(!loadFailed)save();
initProfile({say,download,status:s=>{$('save-state').textContent=s;},visible});let m='comment';try{m=localStorage.getItem('lumo-studio-mode')==='profile'?'profile':'comment';}catch{}setMode(m);if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offline-state').textContent='오프라인 준비 완료 · 이 기기에서 인터넷 없이 편집할 수 있습니다.';reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)say('새 버전이 준비됐습니다. 작업을 저장한 뒤 앱 창을 모두 닫고 다시 열어 주세요.');});});}catch{$('offline-state').textContent='오프라인 준비 실패 · 인터넷 연결 후 다시 열어 주세요.';}}}
init();

for(const id of ['project-filter','safety-filter','search'])$(id).addEventListener(id==='search'?'input':'change',renderList);
$('rename-project').onclick=()=>{const filter=$('project-filter').value;if(!filter.startsWith('p:'))return;const old=filter.slice(2),name=prompt('폴더의 새 이름을 입력하세요. 같은 이름의 폴더가 있으면 합쳐집니다.',old);if(name===null||!name.trim()||name.trim()===old)return;const next=name.trim();if(records.some(r=>r.project===next)&&!confirm('기존 ‘'+next+'’ 폴더로 합칠까요?'))return;records.forEach(r=>{if(r.project===old)r.project=next;});save();populate();$('project-filter').value='p:'+next;renderList();};
$('export-project').onclick=()=>{const filter=$('project-filter').value;if(filter==='all')return;const items=records.filter(r=>matches(r,filter));if(!items.length){say('이 폴더는 비어 있습니다.');return;}download(JSON.stringify({format:'mint-comment-collection',version:2,records:items},null,2),(filter==='unfiled'?'미분류':filter.slice(2)).replace(/[\\/:*?"<>|]/g,'_')+'-project.json','application/json');};
