import {normalize,generate,newKey,esc} from './renderer.js';
const $=id=>document.getElementById(id),STORE='mint-comment-mobile-v1',BACKUP=STORE+'-previous';
let records=[],active='',output='',view='library',timer,messageTimer,dirty=false,loadFailed=false;
const current=()=>records.find(r=>r.key===active);
function say(s){$('message').textContent=s;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').textContent='',6500);}
function save(){clearTimeout(timer);try{if(loadFailed)throw Error();const previous=localStorage.getItem(STORE);if(previous)localStorage.setItem(BACKUP,previous);localStorage.setItem(STORE,JSON.stringify({active,records}));dirty=false;$('save-state').textContent='이 기기에 자동 저장됨';return true;}catch{$('save-state').textContent='기기 저장 실패 · JSON으로 백업해 주세요';dirty=true;return false;}}
function changed(){dirty=true;$('save-state').textContent='저장 중…';clearTimeout(timer);timer=setTimeout(save,350);if(view==='theme'||view==='preview')renderPreview();}
function switchView(next){view=next;document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==next);document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(next==='library')renderList();if(next==='theme'||next==='preview')renderPreview();window.scrollTo(0,0);}
function renderList(){$('characters').innerHTML=records.map(r=>`<article class="character ${r.key===active?'selected':''}"><div class="symbol" style="background:${r.color}" aria-hidden="true">${esc(r.emoji1)}</div><div class="info"><h3>${esc(r.work||'이름 없는 캐릭터')}</h3><p class="small">업데이트 ${r.patches.length}개</p><div class="tools"><button data-open="${r.key}">편집</button><button data-duplicate="${r.key}">복제</button><button data-remove="${r.key}" aria-label="${esc(r.work)} 삭제">삭제</button></div></div></article>`).join('');}
function populate(){const d=current();for(const k of ['work','creator','comment','bgm','color','emoji1','emoji2','tone'])$(k).value=d[k];$('hex').value=d.color;renderPatches();renderPreview();}
function renderPatches(){$('patches').innerHTML=current().patches.map((p,i)=>`<details class="patch" ${i===0?'open':''}><summary>${esc(p.date||'날짜 미지정')} · ${esc(p.title||'새 업데이트')}</summary>${['date','title','added','changed','note'].map((k,n)=>`<label for="patch-${i}-${k}">${['날짜','제목','추가한 내용','수정한 내용','덧붙일 코멘트'][n]}</label>${n<2?`<input id="patch-${i}-${k}" type="${k==='date'?'date':'text'}" data-index="${i}" data-key="${k}" value="${esc(p[k])}">`:`<textarea id="patch-${i}-${k}" rows="3" data-index="${i}" data-key="${k}">${esc(p[k])}</textarea>`}`).join('')}<button class="delete-patch" data-delete="${i}">이 기록 삭제</button></details>`).join('');}
function previewDoc(html){return '<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:6px;background:#f1f2ed">'+html+'</body></html>';}
function renderPreview(){output=generate(current());$('code').value=output;const over=output.length>50000;$('copy').disabled=$('html-save').disabled=over;$('count').textContent=output.length.toLocaleString()+' / 50,000자';$('limit').textContent=over?'50,000자를 넘었습니다. 코멘트나 이전 기록을 줄여 주세요.':'공백과 HTML 코드를 포함한 글자 수입니다.';$('limit').classList.toggle('danger',over);if(view==='preview')$('frame').srcdoc=previewDoc(output);if(view==='theme'){let frame=$('theme-preview').querySelector('iframe');if(!frame){frame=document.createElement('iframe');frame.title='색상과 이모지 헤더 미리보기';frame.setAttribute('sandbox','');$('theme-preview').append(frame);}const noFont=output.replace(/@import[^;]+;/g,'');frame.srcdoc=previewDoc(noFont+'<style>.mcc-body,.mcc-patches,.mcc-divider,.mcc-status{display:none!important}</style>');}}
const safeName=()=> (current().work||'character').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_');
async function download(text,name,type){const blob=new Blob([text],{type}),file=new File([blob],name,{type});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:name});return;}catch(e){if(e.name==='AbortError')return;}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);say('파일 저장 위치를 확인해 주세요.');}
function addRecord(r){r.key=newKey();records.unshift(r);active=r.key;save();populate();switchView('edit');}
$('new').onclick=()=>addRecord(normalize({work:'새 캐릭터',creator:'m1nch0wh4ck',comment:'',bgm:'',color:'#00efb2',emoji1:'👽',emoji2:'✦',patches:[]}));
$('characters').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){active=b.dataset.open;save();populate();switchView('edit');}if(b.dataset.duplicate){addRecord(normalize({...records.find(r=>r.key===b.dataset.duplicate),work:records.find(r=>r.key===b.dataset.duplicate).work+' (복사)'}));}if(b.dataset.remove){const r=records.find(r=>r.key===b.dataset.remove);if(!confirm(`‘${r.work}’을 삭제할까요? 필요한 내용은 먼저 JSON으로 백업해 주세요.`))return;records=records.filter(x=>x.key!==r.key);if(!records.length)records=[normalize({work:'새 캐릭터',creator:'m1nch0wh4ck',patches:[]})];if(active===r.key)active=records[0].key;save();populate();renderList();}};
for(const k of ['work','creator','comment','bgm','color','emoji1','emoji2','tone'])$(k).addEventListener('input',()=>{current()[k]=$(k).value;if(k==='color')$('hex').value=current().color;changed();});
$('hex').oninput=()=>{const valid=/^#[0-9a-f]{6}$/i.test($('hex').value);$('hex').setCustomValidity(valid?'':'# 뒤에 6자리 색상 코드를 입력하세요.');if(valid){current().color=$('hex').value;$('color').value=current().color;changed();}};
$('shuffle').onclick=()=>{current().seed=(current().seed+1)|0;changed();};
$('patches').oninput=e=>{const {index,key}=e.target.dataset;if(key){current().patches[Number(index)][key]=e.target.value;const p=current().patches[Number(index)];e.target.closest('details').querySelector('summary').textContent=(p.date||'날짜 미지정')+' · '+(p.title||'새 업데이트');changed();}};
$('patches').onclick=e=>{const b=e.target.closest('[data-delete]');if(b&&confirm('이 업데이트 기록을 삭제할까요?')){current().patches.splice(Number(b.dataset.delete),1);renderPatches();changed();}};
$('add-patch').onclick=()=>{const d=new Date(),date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');current().patches.unshift({date,title:'',added:'',changed:'',note:''});renderPatches();changed();$('patch-0-title').focus();};
$('export').onclick=()=>download(JSON.stringify(current(),null,2),safeName()+'.json','application/json');
$('backup').onclick=()=>download(JSON.stringify({format:'mint-comment-collection',version:1,records},null,2),'mint-comment-backup.json','application/json');
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10000000)throw Error('10MB 이하의 JSON 파일을 선택해 주세요.');const v=JSON.parse(await f.text()),incoming=(v.format==='mint-comment-collection'?v.records:[v]);if(!Array.isArray(incoming)||!incoming.length||incoming.length>200)throw Error('1~200개 캐릭터가 포함된 백업을 선택해 주세요.');const items=incoming.map(x=>({...normalize(x),key:newKey()}));records.unshift(...items);active=items[0].key;save();populate();renderList();say(items.length+'개 캐릭터를 별도로 추가했습니다.');}catch(err){say(err.message);}finally{e.target.value='';}};
$('copy').onclick=async()=>{renderPreview();if(output.length>50000)return;try{await navigator.clipboard.writeText(output);say('HTML을 복사했습니다. 루모 제작자 코멘트에 붙여넣어 주세요.');}catch{$('code-details').open=true;$('code').focus();$('code').select();$('code').setSelectionRange(0,output.length);say('코드를 길게 눌러 복사해 주세요.');}};
$('select-code').onclick=()=>{$('code').focus();$('code').select();$('code').setSelectionRange(0,output.length);};
$('html-save').onclick=()=>{renderPreview();if(output.length<=50000)download(output,safeName()+'-comment.html','text/html');};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&dirty)save();});window.addEventListener('pagehide',()=>{if(dirty)save();});window.addEventListener('beforeunload',e=>{if(dirty&&!save()){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===STORE){loadFailed=true;$('save-state').textContent='다른 창에서 변경됨 · 현재 내용은 JSON 백업 후 다시 열어 주세요';say('다른 창의 작업을 보호하기 위해 자동 저장을 멈췄습니다.');}});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true;}};
async function init(){try{const raw=localStorage.getItem(STORE);if(raw){const s=JSON.parse(raw);if(!Array.isArray(s.records)||!s.records.length)throw Error();records=s.records.map(normalize);active=records.some(r=>r.key===s.active)?s.active:records[0].key;}}catch{loadFailed=true;$('save-state').textContent='저장 내용 읽기 실패 · 기존 저장소는 덮어쓰지 않습니다';say('저장 내용을 읽지 못했습니다. 보관한 JSON을 불러와 주세요.');}
if(!records.length){try{records=[normalize(await(await fetch('./sample.json')).json())];}catch{records=[normalize({work:'새 캐릭터',creator:'m1nch0wh4ck',patches:[]})];}active=records[0].key;}
populate();renderList();if(!loadFailed)save();if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offline-state').textContent='오프라인 준비 완료 · 이 기기에서 인터넷 없이 편집할 수 있습니다.';reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)say('새 버전이 준비됐습니다. 작업을 저장한 뒤 앱 창을 모두 닫고 다시 열어 주세요.');});});}catch{$('offline-state').textContent='오프라인 준비 실패 · 인터넷 연결 후 다시 열어 주세요.';}}}
init();
